spring:
  data:
    mongodb:
      uri: ${DEV_MONGO_URL}
      auto-index-creation: true
      database: UrbanRides

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  super-admin:
    key: ${SUPER_ADMIN_KEY}

