spring:
  data:
    mongodb:
      uri: ${PROD_MONGO_URL}  # Railway environment variable
      database: UrbanRides
      auto-index-creation: true



server:
  port: ${PORT:8080}

  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

  app:
    super-admin:
      key: ${SUPER_ADMIN_KEY}